/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as AuthenticatedPopupsRouteImport } from './routes/_authenticated/popups'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedLearningCentersRouteImport } from './routes/_authenticated/learning-centers'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedContentWordsRouteImport } from './routes/_authenticated/content/words'
import { Route as AuthenticatedContentLessonsRouteImport } from './routes/_authenticated/content/lessons'
import { Route as AuthenticatedContentCoursesRouteImport } from './routes/_authenticated/content/courses'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPopupsRoute = AuthenticatedPopupsRouteImport.update({
  id: '/popups',
  path: '/popups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningCentersRoute =
  AuthenticatedLearningCentersRouteImport.update({
    id: '/learning-centers',
    path: '/learning-centers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentWordsRoute =
  AuthenticatedContentWordsRouteImport.update({
    id: '/content/words',
    path: '/content/words',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentLessonsRoute =
  AuthenticatedContentLessonsRouteImport.update({
    id: '/content/lessons',
    path: '/content/lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentCoursesRoute =
  AuthenticatedContentCoursesRouteImport.update({
    id: '/content/courses',
    path: '/content/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/popups': typeof AuthenticatedPopupsRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/content/courses': typeof AuthenticatedContentCoursesRoute
  '/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/content/words': typeof AuthenticatedContentWordsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/popups': typeof AuthenticatedPopupsRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/content/courses': typeof AuthenticatedContentCoursesRoute
  '/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/content/words': typeof AuthenticatedContentWordsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/popups': typeof AuthenticatedPopupsRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/content/courses': typeof AuthenticatedContentCoursesRoute
  '/_authenticated/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/_authenticated/content/words': typeof AuthenticatedContentWordsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/coupons'
    | '/learning-centers'
    | '/overview'
    | '/payments'
    | '/popups'
    | '/user-management'
    | '/users'
    | '/'
    | '/content/courses'
    | '/content/lessons'
    | '/content/words'
    | '/errors/$error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/coupons'
    | '/learning-centers'
    | '/overview'
    | '/payments'
    | '/popups'
    | '/user-management'
    | '/users'
    | '/'
    | '/content/courses'
    | '/content/lessons'
    | '/content/words'
    | '/errors/$error'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/coupons'
    | '/_authenticated/learning-centers'
    | '/_authenticated/overview'
    | '/_authenticated/payments'
    | '/_authenticated/popups'
    | '/_authenticated/user-management'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/content/courses'
    | '/_authenticated/content/lessons'
    | '/_authenticated/content/words'
    | '/_authenticated/errors/$error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/popups': {
      id: '/_authenticated/popups'
      path: '/popups'
      fullPath: '/popups'
      preLoaderRoute: typeof AuthenticatedPopupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-centers': {
      id: '/_authenticated/learning-centers'
      path: '/learning-centers'
      fullPath: '/learning-centers'
      preLoaderRoute: typeof AuthenticatedLearningCentersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/words': {
      id: '/_authenticated/content/words'
      path: '/content/words'
      fullPath: '/content/words'
      preLoaderRoute: typeof AuthenticatedContentWordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/lessons': {
      id: '/_authenticated/content/lessons'
      path: '/content/lessons'
      fullPath: '/content/lessons'
      preLoaderRoute: typeof AuthenticatedContentLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/courses': {
      id: '/_authenticated/content/courses'
      path: '/content/courses'
      fullPath: '/content/courses'
      preLoaderRoute: typeof AuthenticatedContentCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedLearningCentersRoute: typeof AuthenticatedLearningCentersRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPopupsRoute: typeof AuthenticatedPopupsRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContentCoursesRoute: typeof AuthenticatedContentCoursesRoute
  AuthenticatedContentLessonsRoute: typeof AuthenticatedContentLessonsRoute
  AuthenticatedContentWordsRoute: typeof AuthenticatedContentWordsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedLearningCentersRoute: AuthenticatedLearningCentersRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPopupsRoute: AuthenticatedPopupsRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContentCoursesRoute: AuthenticatedContentCoursesRoute,
  AuthenticatedContentLessonsRoute: AuthenticatedContentLessonsRoute,
  AuthenticatedContentWordsRoute: AuthenticatedContentWordsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
